### ISSUE TITLE
the embeddings in training process

### ISSUE THREAD

**Issue by hccavgcyv** [callsys/GenPromp#2]
Thanks for the great work!

I have some questions regarding the two types of embeddings, or tokens, mentioned in the paper. 

Prior to the training process, the concept tokens are initialized using the meta tokens. 
However, I would like to clarify what happens once the training commences. 

Do the meta tokens remain static and not participate in the entire training process? Is it solely the concept tokens that are involved throughout the entire training process?

**Comment by callsys** [comment]
Yes, the meta tokens are static, and they are used to initialize the concept tokens before the training process starts.

**Comment by hccavgcyv** [comment]
@callsys 

Thank you soooo much for your response. Perhaps it is my own foolishness, but I still have a little bit of confusion.


Does it mean that during the training process, the discriminative embedding of each image within one category is the same, and the representative embedding is optimized through training? 

What does the phrase 'training for... respectively' in Figure 3? 

During the testing process, if both the prompts are initialized to be the same, wouldn't the same prompt generate two same prompt embeddings? 
Are the discriminative embedding and representative embedding in the testing process encoded from different tokenizer embedding modules?

**Comment by callsys** [comment]
1、Q: “during the training process …”. A: Yes
2、For each category (such as goldfish, bird, and horse), we train a representative embedding (f_r) for it. There is a one-to-one correspondence between categories and representative embeddings.
3、During the testing process, prompt embeddings of the images from the same category are the same, but prompt embeddings of the images from different categories are different.
4、Discriminative embedding and representative embedding in the testing process are encoded from the same tokenizer, but from different token embeddings (i.e., discriminative embedding is encoded from meta token, and representative embedding is encoded from concept token)

**Comment by hccavgcyv** [comment]
Okay, thank you！！ I understand now

**Comment by hccavgcyv** [comment]
Okay, thank you！！ I understand now
