### ISSUE TITLE
Google Drive link does not work

### ISSUE THREAD

**Issue by dhryougit** [callsys/GenPromp#7]
Thank you for your great works. 
I want to use your pretrained weights but your given google drive link does not work. 
And I also tried to download the Baidu file, but the program is all chinese and I failed to download it. 
Can you check the google drive link?

Thank you!

**Comment by callsys** [comment]
Sure, the correct link has been updated!

**Comment by donghunryou** [comment]
Thank you!

**Comment by dhryougit** [comment]
Thank you!
